language: ruby
rvm:
- 2.1.0
branches:
  only:
  - develop
before_install:
- gem install middleman
script:
- bundle exec middleman build
after_success:
- echo ${GH_TOKEN} > ./.git/credentials
- git config user.name ${GH_USER}
- git config user.email ${GH_EMAIL}
- bundle exec middleman deploy
