language: ruby
sudo: false
cache:
  - bundler
rvm:
  - 2.1.0
branches:
  only:
    - develop
env:
  global:
  - GH_COMMIT_AUTHOR="Travis CI"
  - GH_COMMIT_EMAIL=oss+travis-ci@unrulygroup.com
script:
  - bundle exec rake travis:script
after_success:
  - bundle exec rake travis:after_success
